title: 'g0ng014.github.io'
description: "Personal Web."
url: "https://g0ng014.github.io"

header_pages:
  - index.md
  - g0ng0.md
  - about.md
  - contact.md

style: dark

footer: 'Sorry I don't have social networks and neither should you!'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
